// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBID08lIedyxtbfWHMQP4nbHs0BWwyBJRg',
    appId: '1:58006040286:web:66d82904744877aed65c4f',
    messagingSenderId: '58006040286',
    projectId: 'controlemap-7bbc3',
    authDomain: 'controlemap-7bbc3.firebaseapp.com',
    storageBucket: 'controlemap-7bbc3.firebasestorage.app',
    measurementId: 'G-GF32MFGNTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHu4g_Kg1i7gczD76YaMPIotjIw2j040',
    appId: '1:58006040286:android:a1f3a35a3efe57d0d65c4f',
    messagingSenderId: '58006040286',
    projectId: 'controlemap-7bbc3',
    storageBucket: 'controlemap-7bbc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8q-IP1TwchOGwIpPxe2X-McbLCwSHWk',
    appId: '1:58006040286:ios:7ff3bd5d1b1b0e4cd65c4f',
    messagingSenderId: '58006040286',
    projectId: 'controlemap-7bbc3',
    storageBucket: 'controlemap-7bbc3.firebasestorage.app',
    iosClientId: '58006040286-n5s3umflt7gku1ise23b2hogad9tmfja.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlEmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB8q-IP1TwchOGwIpPxe2X-McbLCwSHWk',
    appId: '1:58006040286:ios:7ff3bd5d1b1b0e4cd65c4f',
    messagingSenderId: '58006040286',
    projectId: 'controlemap-7bbc3',
    storageBucket: 'controlemap-7bbc3.firebasestorage.app',
    iosClientId: '58006040286-n5s3umflt7gku1ise23b2hogad9tmfja.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlEmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBID08lIedyxtbfWHMQP4nbHs0BWwyBJRg',
    appId: '1:58006040286:web:31dee59abf884b63d65c4f',
    messagingSenderId: '58006040286',
    projectId: 'controlemap-7bbc3',
    authDomain: 'controlemap-7bbc3.firebaseapp.com',
    storageBucket: 'controlemap-7bbc3.firebasestorage.app',
    measurementId: 'G-VEL5QWTTQ2',
  );
}
